// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Group_3_Week_11_DB_API.Models;

namespace Group_3_Week_11_DB_API.Data
{
    public partial class Wossamotta_UContext : DbContext
    {
        public Wossamotta_UContext()
        {
        }

        public Wossamotta_UContext(DbContextOptions<Wossamotta_UContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Class> Classes { get; set; }
        public virtual DbSet<Faculty> Faculties { get; set; }
        public virtual DbSet<FacultyClass> FacultyClasses { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<StudentSchedule> StudentSchedules { get; set; }
        public virtual DbSet<Subject> Subjects { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Class>(entity =>
            {
                entity.Property(e => e.ClassId)
                    .HasMaxLength(8)
                    .IsUnicode(false)
                    .HasColumnName("ClassID");

                entity.Property(e => e.ClassRoomNumber)
                    .HasMaxLength(25)
                    .IsUnicode(false)
                    .HasColumnName("classRoomNumber");

                entity.Property(e => e.StartDate).HasColumnType("date");
            });

            modelBuilder.Entity<Faculty>(entity =>
            {
                entity.ToTable("Faculty");

                entity.Property(e => e.FacultyId)
                    .HasMaxLength(8)
                    .IsUnicode(false)
                    .HasColumnName("FacultyID");

                entity.Property(e => e.FacFirstName)
                    .HasMaxLength(40)
                    .IsUnicode(false);

                entity.Property(e => e.FacLastName)
                    .HasMaxLength(40)
                    .IsUnicode(false);

                entity.Property(e => e.TenureIsChecked).HasColumnName("Tenure_is_checked");

                entity.Property(e => e.Title)
                    .HasMaxLength(40)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<FacultyClass>(entity =>
            {
                entity.HasKey(e => e.FacultyClassesId)
                    .HasName("PK__Faculty___3192B607E109BBDC");

                entity.ToTable("Faculty_Classes");

                entity.Property(e => e.FacultyClassesId)
                    .HasMaxLength(8)
                    .IsUnicode(false)
                    .HasColumnName("Faculty_ClassesID");

                entity.Property(e => e.ClassId)
                    .HasMaxLength(8)
                    .IsUnicode(false)
                    .HasColumnName("ClassID");

                entity.Property(e => e.FacultyId)
                    .HasMaxLength(8)
                    .IsUnicode(false)
                    .HasColumnName("FacultyID");

                entity.HasOne(d => d.Class)
                    .WithMany(p => p.FacultyClasses)
                    .HasForeignKey(d => d.ClassId)
                    .OnDelete(DeleteBehavior.Cascade)
                    .HasConstraintName("FK__Faculty_C__Class__66603565");

                entity.HasOne(d => d.Faculty)
                    .WithMany(p => p.FacultyClasses)
                    .HasForeignKey(d => d.FacultyId)
                    .OnDelete(DeleteBehavior.Cascade)
                    .HasConstraintName("FK__Faculty_C__Facul__6754599E");
            });

            modelBuilder.Entity<Student>(entity =>
            {
                entity.Property(e => e.StudentId)
                    .HasMaxLength(8)
                    .IsUnicode(false)
                    .HasColumnName("StudentID");

                entity.Property(e => e.StudFirstName)
                    .HasMaxLength(25)
                    .IsUnicode(false);

                entity.Property(e => e.StudLastName)
                    .HasMaxLength(25)
                    .IsUnicode(false);

                entity.Property(e => e.StudMajor)
                    .HasMaxLength(40)
                    .IsUnicode(false);

                entity.Property(e => e.StudPhone)
                    .HasMaxLength(14)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<StudentSchedule>(entity =>
            {
                entity.HasKey(e => e.ScheduleId)
                    .HasName("PK__Student___9C8A5B69E2730BDA");

                entity.ToTable("Student_Schedules");

                entity.Property(e => e.ScheduleId)
                    .HasMaxLength(8)
                    .IsUnicode(false)
                    .HasColumnName("ScheduleID");

                entity.Property(e => e.ClassId)
                    .HasMaxLength(8)
                    .IsUnicode(false)
                    .HasColumnName("ClassID");

                entity.Property(e => e.Grade)
                    .HasMaxLength(1)
                    .IsUnicode(false);

                entity.Property(e => e.StudentId)
                    .HasMaxLength(8)
                    .IsUnicode(false)
                    .HasColumnName("StudentID");

                entity.HasOne(d => d.Class)
                    .WithMany(p => p.StudentSchedules)
                    .HasForeignKey(d => d.ClassId)
                    .OnDelete(DeleteBehavior.Cascade)
                    .HasConstraintName("FK__Student_S__Class__68487DD7");

                entity.HasOne(d => d.Student)
                    .WithMany(p => p.StudentSchedules)
                    .HasForeignKey(d => d.StudentId)
                    .OnDelete(DeleteBehavior.Cascade)
                    .HasConstraintName("FK__Student_S__Stude__693CA210");
            });

            modelBuilder.Entity<Subject>(entity =>
            {
                entity.Property(e => e.SubjectId)
                    .HasMaxLength(8)
                    .IsUnicode(false)
                    .HasColumnName("SubjectID");

                entity.Property(e => e.SubjectCode)
                    .HasMaxLength(25)
                    .IsUnicode(false);

                entity.Property(e => e.SubjectDescription)
                    .HasMaxLength(255)
                    .IsUnicode(false);

                entity.Property(e => e.SubjectName)
                    .HasMaxLength(50)
                    .IsUnicode(false);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}